# Teaching Experience



## **Graduate Teaching Assistant**  

### Summer 2024 
**MCD BIO 187AL: Research Immersion Laboratory in Genomic Biology** (5 units)  
**University of California, Los Angeles (UCLA)**  
*June 2024 – August 2024*  
**Instructor:** [Dr. Lukasz Salwinski](https://scholar.google.com/citations?user=oTgN_eUAAAAJ&hl=en)  

- **Course Resources:**  
  - [Syllabus](assets/MCDB187AL-Summer2024-Syllabus-V2.pdf)  
  - [Students' Reviews](assets/AI_J._-_241_MCD_BIO_187AL_LAB_1B.pdf)  
- **Responsibilities:**  
  - Conducted [lab sessions](https://drive.google.com/drive/folders/17FTYc4qdWfscybALoi85EP3VocD3giV6?usp=drive_link) and held office hours to provide individualized support for students.  
  - Demonstrated bioinformatics tools, including NCBI BLAST, InterProScan, PSIPRED, SignalP, and [ChimeraX](https://drive.google.com/file/d/1g6SUgFxOo0I3-QbX5CxZ0P0ivMQi9Idj/view?usp=sharing).  
  - Mentored students on designing, implementing, and presenting their final research projects.  
  - Evaluated students' progress through weekly quizzes, assignments, and final project presentations.

### Spring 2025
**C&S BIO M187: Research Communication in Computational and Systems Biology** (4 units)  
**University of California, Los Angeles (UCLA)**  
*March 2025 – June 2025*  
**Instructor:** [Dr. Matteo Pellegrini](https://medschool.ucla.edu/people/matteo-pellegrini-phd) 


